#!/usr/bin/env bash
# device_id, to know which room the sound comes from on server
device_id=001
# server ip and port to send collected data to (e.g. http://127.0.0.1:8000)
server=127.0.0.1:80
# timer (time) take sample every (10s/1m/1h etc, 0 to run infinitely)
timer=1m
# audio_duration (time) (1s/10s/1m etc, if timer is 0 this will by IGNORED)
audio_duration=10s
# sample_duration (time) (0.5s/1s/2s etc) - how often do we take audio sample
sample_duration=1s
# send_timer (time) how often we send data to server, if timer is 0 this will be IGNORED
send_timer=1m
# which data to grab from audio (mean,slope/mfcc,skewness/centroid,spread etc)
# possible values are: mfcc/mean/centroid/slope/spread/skewness/kurtosis/decrease/rolloff
data=mean,slope