#!/bin/bash
echo "Running Audiocare Main Script"

./aubio/build/examples/audiocare -v -d 111111111
# ./aubio/build/examples/audiocare -B 2048 -H 2048 -v -i ./hello.wav -d 100000000
# ./aubio/build/examples/audiocare -i ./hello.wav

echo "Whoop! Done"
