#!/bin/bash
echo "Running Spectrm example"

echo $OSTYPE
if [[ "$OSTYPE" == 'msys' ]]; then
    ./aubio/build/examples/aubiocare.exe ./hello.wav
else
    # ./aubio/build/examples/aubiocare
    ./aubio/build/examples/aubiocare -B 2048 -H 2048 -v -i ./hello.wav
    # ./aubio/build/examples/aubiocare -i ./hello.wav
fi

echo "Whoop! Done"