#!/bin/bash
echo "Running Audiocare Main Script"

./aubio/build/examples/audiocare -d 111111111
# ./aubio/build/examples/audiocare ./hello.wav -B -d 111111111
# ./aubio/build/examples/aubiocare -B 2048 -H 2048 -v -i ./hello.wav -d 100000000
# ./aubio/build/examples/aubiocare -i ./hello.wav

echo "Whoop! Done"
