#!/bin/bash
echo "Running Spectrm example"

# ./aubio/build/examples/aubiocare
./aubio/build/examples/aubiocare -B 2048 -H 2048 -v -i ./hello.wav
# ./aubio/build/examples/aubiocare -i ./hello.wav

echo "Whoop! Done"
